SnapTrack.Web/Models/TimeEntryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SnapTrack.Entities.Models;
using System.ComponentModel.DataAnnotations;

namespace SnapTrack.Web.Models
{
    public class TimeEntryViewModel
    {
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{dd/MM/yyyy}")]
        public DateTime DateRecorded { get; set; }
        [Range(0, 24, ErrorMessage = "Time must be between 0 and 24 hours")]
        public double Time { get; set; }
        public WorkItemViewModel WorkItem { get; set; }
        public TimeEntryOption Option { get; set; }

    }
}

SnapTrack.Web/Controllers/TimeEntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SnapTrack.Web.Models;
using SnapTrack.Web.Service;
using Microsoft.AspNet.Identity;
using SnapTrack.Entities.Models;

namespace SnapTrack.Web.Controllers
{
    [Authorize]
    public class TimeEntryController : Controller
    {
        SnapTrackService service = new SnapTrackService();

        [HttpPost]
        public ActionResult Index(TimeEntryViewModel model)
        {
            return PartialView(model);
        }
        
        public ActionResult Edit(int id)
        {
            var model = service.GetTimeEntryViewModelById(id, User.Identity.GetUserId());
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TimeEntryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var projectId = 0;
                var workItemId = 0;
                var project = service.GetProjectNameByExactName(model.WorkItem.Project.Name, User.Identity.GetUserId());
                projectId = project != null ? project.Id : 0;

                if (projectId != 0)
                {
                    var workItem = service.GetWorkItemViewModelByExactName(model.WorkItem.Name, project.Id, User.Identity.GetUserId());
                    workItemId = workItem != null ? workItem.Id : 0;
                }
                else
                {
                    projectId = service.CreateProject(model.WorkItem.Project.Name, User.Identity.GetUserId());
                }

                if (workItemId == 0)
                {
                    workItemId = service.CreateWorkItem(model.WorkItem.Name, projectId.ToString(), User.Identity.GetUserId());
                }
                service.SaveTimeEntry(model.Id, model.Time, model.Option, workItemId, User.Identity.GetUserId());
                return PartialView("Index", model);
            }

            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Approve(int id)
        {
            var model = service.GetTimeEntryViewModelById(id, User.Identity.GetUserId());
            model.Option = TimeEntryOption.TimeBlock;
            service.SaveTimeEntry(model.Id, model.Time, model.Option, model.WorkItem.Id, User.Identity.GetUserId());
            return PartialView("Index", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            service.DeleteTimeEntry(id, User.Identity.GetUserId());
            return new EmptyResult();
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TimeEntryViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                var projectId = 0;
                var workItemId = 0;
                var project = service.GetProjectNameByExactName(model.WorkItem.Project.Name, User.Identity.GetUserId());
                projectId = project != null ? project.Id : 0;

                if (projectId != 0)
                {

                    var workItem = service.GetWorkItemViewModelByExactName(model.WorkItem.Name, project.Id, User.Identity.GetUserId());
                    workItemId = workItem != null ? workItem.Id : 0;
                }
                else
                {
                    projectId = service.CreateProject(model.WorkItem.Project.Name, User.Identity.GetUserId());
                }

                if (workItemId == 0)
                {
                    workItemId = service.CreateWorkItem(model.WorkItem.Name, projectId.ToString(), User.Identity.GetUserId()); 
                }

                service.CreateTimeEntry(model.DateRecorded, model.Time, model.Option, workItemId.ToString(), User.Identity.GetUserId());

                return PartialView();
            }
            return PartialView(model);
            
        }
    }
}

SnapTrack.Web/Views/TimeEntry/Create.cshtml
@using SnapTrack.Entities.Models;
@model TimeEntryViewModel

@{
    ViewBag.Title = "Time Entry";
}

@using (Ajax.BeginForm("Create", "TimeEntry", new AjaxOptions()
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "create-wrapper",
    OnSuccess = "loadCreateTimeEntryForm"
}))
    {
        @Html.AntiForgeryToken()
        <div class="panel panel-default">
            <div class="panel-heading">
                <div id="myTab">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#TimeBlock" data-toggle="tab" onclick="setTimeEntryOption('TimeBlock');">Time Block</a></li>
                       @* <li><a href="#Appointment" data-toggle="tab" onclick="setTimeEntryOption('Appointment');">Appointment</a></li>*@
                    </ul>
                </div>
                
            </div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-xs-2">Project</label>
                        <div class="col-xs-10">
                            @Html.TextBoxFor(model => model.WorkItem.Project.Name, new { @class = "form-control", @placeholder = "Project", @id = "Create-ProjectName" })
                            @Html.ValidationMessageFor(model => model.WorkItem.Project.Name, "", new { @class = "text-danger help-block" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-2">Task</label>
                        <div class="col-xs-10">
                            @Html.TextBoxFor(model => model.WorkItem.Name, new { @class = "form-control", @placeholder = "Task", @id = "Create-WorkItemName" })
                            @Html.ValidationMessageFor(model => model.WorkItem.Name, "", new { @class = "text-danger help-block" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-2">Time (Hours)</label>
                        <div class="col-xs-10">
                            @Html.TextBoxFor(model => model.Time, new { @class = "form-control", @placeholder = "Time (Hours)", @id = "Create-WorkItemTime" })
                            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger help-block" })
                        </div>
                    </div>
                </div>

                @Html.HiddenFor(model => model.Option)
                @Html.HiddenFor(model => model.DateRecorded, new { @id = "Create-DateRecorded" })

                @Html.HiddenFor(model => model.WorkItem.Project.Id, new { @id = "Create-ProjectId" })
                @Html.HiddenFor(model => model.WorkItem.Id, new { @id = "Create-WorkItemId" })
                
                <div class="form-group">
                    <div class="tab-content col-xs-offset-2" id="tabs">

                        <div id="TimeBlock" class="tab-pane active">
                            <input class="btn btn-primary" type="submit" value="Add" />
                        </div>
                        <div id="Timer" class="tab-pane">

                        </div>
                        <div id="Appointment" class="tab-pane">

                            <input type="submit" value="Add" />
                        </div>
                    </div>
                </div>
                    

            </div>
        </div>

                    }

SnapTrack.Web/Views/TimeEntry/Edit.cshtml
@using SnapTrack.Entities.Models;
@model TimeEntryViewModel

@{
    ViewBag.Title = "Time Entry";
}

@using (Ajax.BeginForm("Edit", new AjaxOptions()
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "timeentry-wrapper-" + Model.Id
}))
{
    @Html.AntiForgeryToken()
    <div class="timeentry-wrapper-@(Model.Id)">
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="nav nav-tabs">
                    @*<li><a href="#TimeBlock-@(Model.Id)" data-toggle="tab" onclick="setTimeEntryOption('TimeBlock', @Model.Id);">Time Block</a></li>
                    <li><a href="#Timer-@(Model.Id)" data-toggle="tab" onclick="setTimeEntryOption('Timer', @Model.Id);">Timer</a></li>
                    <li><a href="#Appointment-@(Model.Id)" data-toggle="tab" onclick="setTimeEntryOption('Appointment', @Model.Id)">Appointment</a></li>*@
                </ul>
            </div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-xs-2">Project</label>
                        <div class="col-xs-10">
                            @Html.TextBoxFor(model => model.WorkItem.Project.Name, new { @class = "form-control", @placeholder = "Project", @id = "Edit-ProjectName-" + Model.Id.ToString() })
                            @Html.ValidationMessageFor(model => model.WorkItem.Project.Name, "", new { @class = "text-danger help-block" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-2">Task</label>
                        <div class="col-xs-10">
                            @Html.TextBoxFor(model => model.WorkItem.Name, new { @class = "form-control", @placeholder = "Task", @id = "Edit-WorkItemName-" + Model.Id.ToString() })
                            @Html.ValidationMessageFor(model => model.WorkItem.Name, "", new { @class = "text-danger help-block" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-2">Time (Hours)</label>
                        <div class="col-xs-10">
                            @Html.TextBoxFor(model => model.Time, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger help-block" })
                        </div>
                    </div>
                </div>
                @Html.HiddenFor(model => model.WorkItem.Id, new { @id = "Edit-WorkItemId-" + Model.Id.ToString() })
                @Html.HiddenFor(model => model.WorkItem.Project.Id, new { @id = "Edit-ProjectId-" + Model.Id.ToString() })
                @Html.HiddenFor(model => model.DateRecorded)
                @Html.HiddenFor(model => model.Option, new { htmlAttributes = new { id = "timeentry-option-" + Model.Id } })

                <div class="form-inline col-xs-offset-2">
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Save" />
                    </div>
                </div>
                
                @*@{
                    if (Model.Option == TimeEntryOption.Appointment || Model.Option == TimeEntryOption.TimeBlock)
                    {
                        @: @Html.LabelFor(model => model.Time): @Html.EditorFor(model => model.Time)
                        @: @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                        <input type="submit" value="Save" />
                    }
                    else if (Model.Option == TimeEntryOption.Timer)
                    {
                        <input type="submit" value="Start Timer" />
                    }
                }*@
                @*<div class="tab-content" id="tabs">
                    <div id="TimeBlock-@(Model.Id)" class="tab-pane">
                        
                        <input type="submit" value="Save" />
                    </div>
                    <div id="Timer-@(Model.Id)" class="tab-pane">
                        @Html.LabelFor(model => model.Time): @Html.EditorFor(model => model.Time)
                        
                    </div>
                    <div id="Appointment-@(Model.Id)" class="tab-pane">
                        @Html.LabelFor(model => model.Time): @Html.EditorFor(model => model.Time)
                        <input type="submit" value="Save" />
                    </div>
                </div>*@
                
            </div>
        </div>
    </div>
}

SnapTrack.Web/Views/TimeEntry/Index.cshtml
@using SnapTrack.Entities.Models;
@model TimeEntryViewModel

@{ 
    ViewBag.Title = "Time Entry";
}

<div id="timeentry-wrapper-@(Model.Id)">
    <div class="panel panel-default">
        <div class="panel-heading">@Html.ValidationSummary(true, "", new { @class = "text-danger" })</div>
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-xs-2">Project</label>
                    <div class="col-xs-10">
                        @Html.TextBoxFor(model => model.WorkItem.Project.Name, new { @class = "form-control", @placeholder = "Project", @readonly = true })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-xs-2">Task</label>
                    <div class="col-xs-10">
                        @Html.TextBoxFor(model => model.WorkItem.Name, new { @class = "form-control", @placeholder = "Task", @readonly = true })
                    </div>

                </div>
                <div class="form-group">
                    <label class="control-label col-xs-2">Time (Hours)</label>
                    <div class="col-xs-10">
                        @Html.TextBoxFor(model => model.Time, new { @class = "form-control", @placeholder = "Time (Hours)", @readonly = true })
                    </div>
                </div>
            </div>

            
            @Html.HiddenFor(model => model.WorkItem.Id)
            @Html.HiddenFor(model => model.WorkItem.Project.Id)
            @Html.HiddenFor(model => model.DateRecorded)

            @if (Model.Option == TimeEntryOption.Appointment)
            {
                @Ajax.BeginForm("Approve", "TimeEntry", new { id = Model.Id }, new AjaxOptions()
               {
                   HttpMethod = "Post",
                   UpdateTargetId = "timeentry-wrapper-" + Model.Id
               });
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Approve" />
                }

            }
            else if (Model.Option == TimeEntryOption.Timer)
            {
                <input type="text" name="timer" class="form-control timer" placeholder="0 sec" />
                <input type="submit" value="Start Timer" />
            }
        <div class="form-inline col-xs-offset-2">
            <div class="form-group">
                @Ajax.ActionLink("Edit", "Edit", "TimeEntry", new { id = Model.Id }, new AjaxOptions()
           {
               HttpMethod = "GET",
               AllowCache = false,
               InsertionMode = InsertionMode.Replace,
               UpdateTargetId = "timeentry-wrapper-" + Model.Id,
               OnSuccess = "initializeEditForm(" + Model.Id + ")"
           }, new { @class = "btn btn-primary" })
            </div>
            <div class="form-group">
                @using (Ajax.BeginForm("Delete", "TimeEntry", new { id = Model.Id }, new AjaxOptions()
                {
                    HttpMethod = "Post",
                    UpdateTargetId = "timeentry-wrapper-" + Model.Id
                }))
                {
                    @Html.AntiForgeryToken()
                    <input class="btn btn-primary" type="submit" value="Delete" />
                }
            </div>

        </div>
            



        </div>
    </div>
</div>